<!-- netlify.toml -->
[build]
  command = "echo 'Build complete'"
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "netlify dev"
  port = 8888
